name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --release -- -D warnings
      - run: cargo build --release
